int Constants::MODE_IS_INCLUDE = 1;
int Constants::MODE_IS_EXCLUDE = 2;
int Constants::CHANGE_TO_INCLUDE_MODE = 3;
int Constants::CHANGE_TO_EXCLUDE_MODE = 4;

int Constants::REPORT_TYPE = 0x22;

int Defaults::ROBUSTNESS_VARIABLE = 2;
int Defaults::QUERY_INTERVAL = 125;
int Defaults::QUERY_RESPONSE_INTERVAL = 100;
int Defaults::GROUP_MEMBERSHIP_INTERVAL = ROBUSTNESS_VARIABLE *QUERY_INTERVAL + QUERY_REPSONSE_INTERVAL;
int Defaults::OTHER_QUERIER_PRESENT_INTERVAL = ROBUSTNESS_VARIABLE * QUERY_INTERVAL + 1/2*QUERY_RESPONSE_INTERVAL;
int Defaults::STARTUP_QUERY_INTERVAL = 1/4 * QUERY_RESPONSE_INTERVAL;
int Defaults::STARTUP_QUERY_COUNT = ROBUSTNESS_VARIABLE;
int Defaults::LAST_MEMBER_QUERY_INTERVAL = 10;
int Defaults::LAST_MEMBER_QUERY_COUNT = ROBUSTNESS_VARIABLE;
int Defaults::LAST_MEMBER_QUERY_TIME = LAST_MEMBER_QUERY_INTERVAL * LAST_MEMBER_QUERY_COUNT;
int Defaults::UNSOLICITED_REPORT_INTERVAL = 1;
//int Defaults::OLDER_VERSION_QUERIER_PRESENT_TIMEOUT;
//int Defaults::OLDER_HOST_PRESENT_INTERVAL;